### ISSUE TITLE
Support binary last will message

### ISSUE THREAD

**Issue by paul-lysak** [vert-x3/vertx-mqtt#128]
At the moment it's only possible to use text Last Will messages because `MqttWill.getWillMessage` returns `String`.
MQTT brokers should also support binary messages, so it should be a byte array instead.
In fact, `MqttConnectPayload.willMessage` which is used to populate that field is deprecated in `netty-codec-mqtt`,
it's suggested to use `MqttConnectPayload.willMessageInBytes` instead.
Can we have an actual data stored as byte array in `MqttWill` and existing method `getWillMessage` turned into the wrapper
doing something like `new String(willMessage, CharsetUtil.UTF_8)`?

**Comment by ppatierno** [comment]
@paul-lysak thanks for the PR, I left a comment there.

**Comment by paul-lysak** [comment]
@ppatierno yes, I saw it and fixed.
