### ISSUE TITLE
Server must send CONNACK 0x01 if CONNECT contains unsupported version of protocol

### ISSUE THREAD

**Issue by paul-lysak** [vert-x3/vertx-mqtt#132]
*Expected behavior:* in accordance with section 3.1.2.2 of MQTT Spec (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html) "The Server MUST respond to the CONNECT Packet with a CONNACK return code 0x01 (unacceptable protocol level) and then disconnect the Client if the Protocol Level is not supported by the Server" 

*Actual behavior:* connection is closed by the server without sending CONNACK. Can be checked with `TC_MQTT_BROKER_CONNACK_005` test case from Eclipse IoT-Testware MQTT Test Suite (https://iottestware.readthedocs.io/en/master/mqtt_test_suite.html). 

*Investigation details:* actual check of protocol version is done by `io.netty.handler.codec.mqtt.MqttVersion.fromProtocolNameAndLevel` which throws `MqttUnacceptableProtocolVersionException`.
It's picked by `io.vertx.mqtt.impl.MqttServerConnection.handleMessage` as a failed `DecoderResult` and pushed further through `chctx.pipeline().fireExceptionCaught(result.cause());`.
Finally it gets to `io.vertx.core.net.impl.VertxHandler.exceptionCaught` which closes the channel. It appears to me that `MqttServerConnection.handleMessage` is the right place to give the 
`MqttUnacceptableProtocolVersionException` special treatment and send `CONNACK` prior to closing the connection.

**Comment by vietj** [comment]
can you write a reproducer in Vertx MQTT testsuite to demonstrate this ?

**Comment by vietj** [comment]
@paul-lysak can you look at https://github.com/vert-x3/vertx-mqtt/tree/handle-unsupported-protocol-version and check if that works for you ?

**Comment by vietj** [comment]
if that's fine then it can be in 3.8 thanks for the detailed analysis it was helpful

**Comment by ppatierno** [comment]
@vietj can you open a PR please so that I can review and discuss on this?

**Comment by vietj** [comment]
done @ppatierno

**Comment by paul-lysak** [comment]
@vietj appears to be good, thank you
