### ISSUE TITLE
mqttClient qos2inbound queue   keeps growing

### ISSUE THREAD

**Issue by lifengchuan2008** [vert-x3/vertx-mqtt#133]
When does the qos2inbound queue release when qos2?
![image](https://user-images.githubusercontent.com/15622265/57354306-b612cb80-719d-11e9-8c5f-fa28691300e5.png)

I have an application that USES MQTT qos2 to send and receive messages and watch the memory usage grow.

The mat analysis is as follows:

![image](https://user-images.githubusercontent.com/15622265/57356935-4c49f000-71a4-11e9-8182-7955f85f4eb4.png)

**Comment by vietj** [comment]
it looks like a leak

**Comment by vietj** [comment]
how do you reproduce this ? what is your scenario ?

**Comment by vietj** [comment]
this is definitely a bug, there is a bug fix for this coming in 3.8
