### ISSUE TITLE
Mqtt Server Use Boring SSL  cause memory leak 

### ISSUE THREAD

**Issue by leeflying315** [vert-x3/vertx-mqtt#146]
MQTT server use boring ssl, netty-tcnative-boringssl-static version is latest 2.0.25Final. At first, momory incresed normal, but when client connection is closed, none heap memory still can't free. I used full GC, the none-headp memory still unchanged. 
It confused me serveral daya, should i do something to release open ssl context？or it's a bug？

**Comment by leeflying315** [comment]
After several days tests , the server occupys too much memory , but it has a top value and dosen't release memory, which is bigger than heap momory a lot. it confused me , i use visualvm and invoke netty direct , the direct value is  32MB ,and doesn't increase. So what is the excess memory?

can anyone explain this? Thanks

**Comment by vietj** [comment]
can you make a reproducer for this ? have you looked at Netty's issue tracker to find such issue ?

**Comment by leeflying315** [comment]
thanks, I search lots of informations, but no issue seems to related to this. Cloud u explain why momory cloudn't release ? or i misconfigure some params.
