### ISSUE TITLE
exceptionHandler not work

### ISSUE THREAD

**Issue by sdvdxl** [vert-x3/vertx-mqtt#150]
I set the exceptionHandlers :

```java
Vertx vertx Vertx.vertx(vertxOptions).exceptionHandler(t -> log.error(t.getMessage(), t));
MqttServer mqttServer =
        MqttServer.create(vertx).exceptionHandler(t -> log.error(t.getMessage(), t));

endpoint.exceptionHandler(t -> log.error(t.getMessage(), t));
```
 and the code will throw NullException if not set auth info : 

`endpoint.auth().toJson()`

but no errors were printed, and not running into the handler using debug, but in vetrx InboundBuffer.java , exceptionHandler is null 

```
private void handleException(Throwable err) {
    Handler<Throwable> handler;
    synchronized (this) {
      if ((handler = exceptionHandler) == null) {
        return;
      }
    }
    handler.handle(err);
  }
```

Is there something wrong?

**Comment by alexei-osipov** [comment]
The exception handler that you need to set is the MqttServerImpl.server.exceptionHandler.

The problem that Vert.x API for MqttServer does not provide any means to reach MqttServerImpl.server and set that handler.

So, yes, MqttServer.exceptionHandler does not work (as expected).

**Comment by vietj** [comment]
this should be reported now in 3.9.0 since we fixed this issue https://github.com/eclipse-vertx/vert.x/commit/c2bb2e8a8bce380467fddb80d10197749ff21349#diff-464255635b4e404921051fc7ba93471f

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3272
