### ISSUE TITLE
MqttClient.isConnected() returns true after call to MqttClient.disconnect()

### ISSUE THREAD

**Issue by mhball** [vert-x3/vertx-mqtt#151]
The following Kotlin snippet prints true.
```
mqttClient.disconnect {
    if(it.succeeded()) {
        println(mqttClient.isConnected)
}
```

It seems an intentional disconnect doesn't set the isConnected flag to false.

**Comment by vietj** [comment]
actually it does but once the TCP connection is closed, I think it should be done before

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-mqtt/pull/179
