### ISSUE TITLE
MQTT client dies if the broker does not send a CONNACK message

### ISSUE THREAD

**Issue by deen13** [vert-x3/vertx-mqtt#159]
### Version

4.0.0-SNAPSHOT

### Context

I encountered an exception which looks suspicious while implementing the reconnect mechanism of our service. I'd like our verticle to retry the initial connection until the broker is up and running which works quiet well if the broker is fast enough. Otherwise, if the broker accepts the TCP connection but does not send a CONNACK message, the connectPromise() is not called and the verticle is stuck.

### Reproducer

I've made a simple repository to demonstrate the behaviour. 

* https://github.com/deen13/vertx-reconnect

### Steps to reproduce

1. Start the Verticle without having the broker up and running
2. Wait until the first connect attempt fails
3. Start the broker
4. Wait for the established connection 
5. Publish a message on the `test` topic

### Extra

The reconnect mechanism works if the retry interval is higher and the vernemq has some time to start. I wonder if this is a bug within this library or if the broker does not behave correctly.

**Comment by vietj** [comment]
do you know if that happens in 3.9 ?

**Comment by deen13** [comment]
Sorry the version might be misleading. Yes that behaviour is exact the same in 3.9.1.

**Comment by deen13** [comment]
I've just encountered that the client is also stuck if it retries to connect in the `closeHandler` immediately after the broker has closed the connection and therefore is within the shutdown process.

**Comment by deen13** [comment]
[Specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033):

> If the Client does not receive a CONNACK Packet from the Server within a reasonable amount of time, the Client SHOULD close the Network Connection. A "reasonable" amount of time depends on the type of application and the communications infrastructure.

**Comment by vietj** [comment]
can you provide an actual reproducer ? I tried to reproduce but could not. For the second case I tried also with master and it works, I added a test for this in https://github.com/vert-x3/vertx-mqtt/commit/f3cab009d8dd70fd84ff8f66a6ee344a07be75da
