### ISSUE TITLE
Possible memory leak when using many MqttClient instances one after another

### ISSUE THREAD

**Issue by mbaeuerle** [vert-x3/vertx-mqtt#164]
### Questions

-

### Version

Which version(s) did you encounter this bug ?
3.9.1

### Context

The setup is as follows:
A Vert.X MqttClient is created, connecting, sending/receiving some data and then closing the connection again.
This is done multiple times per minute each time a new MqttClient is created, overwriting the last one.
It seems after ca 2h the JVM uses 200-300MB more memory than before and increases even more.

### Do you have a reproducer?

Unfortunately not.

### Steps to reproduce

1. Create MqttClient
2. Connect to Broker
3. Receive some message
4. Disconnect
5. Start again at 1

### Extra

* Using VisualVM I looked at the diff between two snapshots some hours apart. There it looked like during this time many additional (in this case over 700) `NetClientImpl` objects were allocated but no new `MqttClientImpl`.
* When checking the code I noticed that the `MqttClientImpl` is connecting via the `NetClient`:
  https://github.com/vert-x3/vertx-mqtt/blob/d51c272d4de5dd148843f5a6b30bfadfaee26185/src/main/java/io/vertx/mqtt/impl/MqttClientImpl.java#L195
  But disconnection is not done by calling `client.close()` but by closing the connection directly:
  https://github.com/vert-x3/vertx-mqtt/blob/d51c272d4de5dd148843f5a6b30bfadfaee26185/src/main/java/io/vertx/mqtt/impl/MqttClientImpl.java#L275
  Maybe this misses some of the clean up steps which are done when calling `NetClientImpl.close()`:
  https://github.com/eclipse-vertx/vert.x/blob/581ce8d8ff55652269030d20d9fc95b0ac1b1808/src/main/java/io/vertx/core/net/impl/NetClientImpl.java#L120-L133

**Comment by vietj** [comment]
can you perform a heap dump when this happens and post it somewhere ?

**Comment by sophokles73** [comment]
Here's a Gist with a reproducer: https://gist.github.com/sophokles73/84965340c3098478a6a2a1164cecbb67
And a profiler snapshot that can be opened with VisualVM. The snapshot has been taken after about 2500 connect/dsiconnect cycles using the gist above.
[vertx-mqtt-client-snapshot-1598274789602.zip](https://github.com/vert-x3/vertx-mqtt/files/5118026/vertx-mqtt-client-snapshot-1598274789602.zip)

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
scheduled for 3.9.3 - any help wanted!

**Comment by sophokles73** [comment]
I have run the test against vertx-mqtt master which is based on vert.x 4.0.0-SNAPSHOT. The problem doesn't occur there which is probably due to some changes in the NetClientImpl class there.
In any case, it seems to be the right thing for the MqttClientImpl to close the NetClientImpl instead of just the NetSocketImpl in any case so I will create a corresponding PR against master which can then also be backported to the 3.9 branch ...
