### ISSUE TITLE
vertx-mqtt Auto keep alive not working 

### ISSUE THREAD

**Issue by AlmostRuio** [vert-x3/vertx-mqtt#183]
Vert.x 4.0.0.CR2

The auto keep alive in MqttClientOptions seems not to be working. 

Reproducer:
https://github.com/AlmostRuio/vertx-mqtt-timeout

Reproduce: build the project and run the Main:
- Every 30-40 seconds the connection is lost.

Client is my code, server from [examples](https://github.com/vert-x3/vertx-examples/blob/4.x/mqtt-examples/src/main/java/io/vertx/example/mqtt/app/Server.java)

**Comment by vietj** [comment]
I'll try solving this before 4.0.0 GA

**Comment by vietj** [comment]
thanks for the reproducer, indeed sending message prevents sending ping req, I'll investigate

**Comment by vietj** [comment]
@AlmostRuio can you have a look https://github.com/vert-x3/vertx-mqtt/pull/186 ?

**Comment by AlmostRuio** [comment]
> @AlmostRuio can you have a look #186 ?

Sorry I missed the request, have a nice day.
