### ISSUE TITLE
Subscriber is disconnected by broker when using QoS0 and frequently receiving messages

### ISSUE THREAD

**Issue by 0yves0** [vert-x3/vertx-mqtt#188]
This issue has been opened after a discussion with Julien on the Vertx user group. https://groups.google.com/g/vertx/c/CKYmKsmtGjA/m/nL85dtFMBAAJ

### Version
Found in 3.9.4
Repoduced in 3.9.5 & 4.0.0 

### Context

After updating my application from Vert.x 3.9.3 to 3.9.4 and made the appropriate changes due to new deprecated features, I encountered MQTT client disconnections when subscribing to a topic using QoS0 and keep alive enabled. From broker side, client is disconnected due to a keep alive interval not respected.

### Do you have a reproducer?

 - 1 client subscribing with QoS0 and default keep alive interval value
 - 1 server sending a message to the client each 2 sec
 - client is disconnected after ~45 sec 

https://github.com/0yves0/vertx-mqtt-qos0-keepalive

**Comment by vietj** [comment]
@0yves0 thanks for the reproducer, so it is a similar issue that was fixed previously in the commit I exhibited but this time with the server sending messages that we did not care about when fixing the client sending messages case.
