### ISSUE TITLE
Unable to control ackowledgement of the message

### ISSUE THREAD

**Issue by ctron** [vert-x3/vertx-mqtt#200]
Currently it is not possible to control the acknowledgement of an MQTT message, as the client auto-acknowledges messages.

### Version

* 3.9.x
* 4.1.x

### Context

Receiving messages.

### Extra

Using QoS 1, the client currently auto-acknowledges messages received from a server, it also does this before calling the user provided handler:

https://github.com/vert-x3/vertx-mqtt/blob/5455c484347bdaf854fdd556653ea37b29ff860d/src/main/java/io/vertx/mqtt/impl/MqttClientImpl.java#L1191-L1195

Taking a look at section "4.3.2" and figure "Figure 4.2" of the MQTT v3.1.1 spec, you can see that the acknowledgement must be sent, **after** the receiver has taken ownership of the message.

However, the MQTT client being an un-opinionated MQTT client, should not acknowledge a message before it has passed it on the application level code, which ultimately takes ownership of the message.

**Comment by vietj** [comment]
does it mean that the message object could have an `ack()` method and we should have an auto-ack message option that would perform the current ack for retro compatibility ?

**Comment by ppatierno** [comment]
I would agree with Julien but leaving autoack as default for backward compatibility of course.

**Comment by tsegismont** [comment]
@ctron would you like to contribue?

**Comment by SivaAkiro** [comment]
can i take this feature? Please provide some information regarding this?

**Comment by vietj** [comment]
@SivaAkiro yes you can, you can read the contribution guidelines

- https://github.com/vert-x3/.github/blob/478611907c326b37f676db4e3657b19278aa64cb/CONTRIBUTING.md

**Comment by SivaAkiro** [comment]
Thanks, can I get some.information about this ticket.

**Comment by SivaAkiro** [comment]
Thanks, can I get some.information about this ticket.

**Comment by vietj** [comment]
- a `ack` method should be added to the message interface
- options would have an auto-ack boolean config that automatically ack the message on behalf of the user and that would be the default behavior
- when auto-ack is set to false, user has to call ack() to acknowledge the message

**Comment by SivaAkiro** [comment]
Question, Options means MQTTClientOptions right?

**Comment by vietj** [comment]
yes and also server options

**Comment by SivaAkiro** [comment]
For QoS 1 every message, we need to check the whether this message should be auto ack or not. Default, all the messages will get auto-ack, if not user has to manually call the ack method.

We need to add the isAutoAck() in MqttPublishMessage Class and all the message which is received by the Client, will validate against this param? 

Is my understanding correct?

**Comment by ppatierno** [comment]
No, you have the auto-ack boolean flag in the options ... so you have to check against it. A PUBLISH message cannot bring the information that it has to be auto-ack or not. It's a client or server configuration as we said.

**Comment by dometec** [comment]
I all, I think this issue can be closed since #235 is merged.

**Comment by ppatierno** [comment]
Closed with #235
