### ISSUE TITLE
Can't connect to mosquitto 2.0 anymore

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-mqtt#207]
With Vert.x 4.2.0.Beta1, I can't connect to Mosquitto anymore.

I uses this test:

```java
package io.vertx.mutiny.mqtt;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;

import org.junit.After;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Test;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;

import io.netty.handler.codec.mqtt.MqttConnectReturnCode;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mutiny.core.Vertx;
import io.vertx.mutiny.mqtt.messages.MqttConnAckMessage;

public class MqttClientTest {

    @ClassRule
    public static GenericContainer<?> mosquitto = new GenericContainer<>("eclipse-mosquitto:2.0")
            .withExposedPorts(1883)
            .withClasspathResourceMapping("mosquitto.conf", "/mosquitto/config/mosquitto.conf", BindMode.READ_ONLY)
            .waitingFor(Wait.forLogMessage(".*mosquitto .* running.*", 1));
    private Vertx vertx;

    @Before
    public void setUp() {
        vertx = Vertx.vertx();
        assertThat(vertx, is(notNullValue()));
    }

    @After
    public void tearDown() {
        vertx.closeAndAwait();
    }

    @Test
    public void test() {
        MqttClient client = MqttClient.create(vertx, new MqttClientOptions().setAutoGeneratedClientId(true));
        MqttConnAckMessage connection = client
                .connect(mosquitto.getMappedPort(1883), mosquitto.getContainerIpAddress())
                .await().indefinitely();
        assertThat(connection, is(notNullValue()));
        assertThat(connection.code(), is(MqttConnectReturnCode.CONNECTION_ACCEPTED));
        client.disconnectAndAwait();
    }

}

```

With Vert.x 4.1.3, it connects and everything is fine. With 4.2.0.Beta1, the same test gets a failure with "Closed" as the message.

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
it is a migration issue to mosquitto 2.0, you need to add `listener 1883` in `mosquitto.conf` see https://mosquitto.org/documentation/migrating-to-2-0/#listener-behaviour-changes

**Comment by cescoffier** [comment]
Hum, it was already using mosquitto 2.0 before, but if that works, I'm good with it.

**Comment by vietj** [comment]
When I looked at the wireshark capture, the server is closing the
connection before receiving the CONNECT message sent by the client.

then I tried your reproducer with other Vert.x versions and it failed the
same way.

you can run the image docker with your config and then do on the terminal :
nc localhost 1883

you will see it gets automatically disconnected whatsoever (normally the
server should hang waiting for the CONNECT msg sent by the client.

**Comment by cescoffier** [comment]
Ok.. so... the image hashes are different... Invisible update, great!

Anyway, thanks for your help! I've added the missing line and everything works.

**Comment by vietj** [comment]
no worries, I reused your code to add an integration test in vertx-mqtt
with the mosquitto image :-)
