### ISSUE TITLE
 property is not assigned correctly

### ISSUE THREAD

**Issue by double-7** [vert-x3/vertx-mqtt#211]
https://github.com/vert-x3/vertx-mqtt/blob/9b8d4ab940c8f58af9e5c168542edb0e67f4fe65/src/main/java/io/vertx/mqtt/impl/MqttEndpointImpl.java#L445

The 'mqttproperties' property is not assigned correctly

**Comment by vietj** [comment]
can you elaborate ?

**Comment by double-7** [comment]
> 你能详细说明一下吗？
` public MqttEndpointImpl subscribeAcknowledge(int subscribeMessageId, List<MqttSubAckReasonCode> reasonCodes, **MqttProperties properties**) {
    return subscribeAcknowledgeWithCode(subscribeMessageId,
      reasonCodes.stream().mapToInt(MqttSubAckReasonCode::value).toArray(),
      **MqttProperties.NO_PROPERTIES**);
  }`

The above is the code I think is defective, and the following is what I fixed

`    public MqttEndpointImpl subscribeAcknowledge(int subscribeMessageId, List<MqttSubAckReasonCode> reasonCodes, **MqttProperties properties**) {
        return subscribeAcknowledgeWithCode(subscribeMessageId,
                reasonCodes.stream().mapToInt(MqttSubAckReasonCode::value).toArray(),
                **properties**);
    }`

**Comment by vietj** [comment]
ah right

**Comment by vietj** [comment]
fixed thanks
