### ISSUE TITLE
Maximum MQTT msg payload with Websockets is limited to 64KB

### ISSUE THREAD

**Issue by vogler75** [vert-x3/vertx-mqtt#216]
### Version

Version 4.2.6

### Context

I have tried to set the MaximumMessageSize to greater than 64k, but this does not work with Websockets. When I set it to greater than 64k, a client which sends a message bigger than 64k gets disconnected. 

### Do you have a reproducer?

https://github.com/vogler75/automation-gateway
But it is not a simple one. 

### Steps to reproduce

1. ... start Vertx based MQTT Server program with UseWebsockets(true) and SetMaxMessageSize(128*1024)
2. ...connect MQTT client and publish a message with more than 64*1024 bytes
3. ...client gets disconnected

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-mqtt/pull/218
