### ISSUE TITLE
Add Mutiny bindings for MQTT Client/Server

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/vertx-mqtt#229]
#### Describe the feature

Currently, there do not appear to be any Mutiny bindings for the 4.x Vert.x versions of MQTT client/server. I would like to be able to use Mutiny with MQTT.

#### Use cases

It would allow developers to not have to mix reactive stream/async coordination mechanisms in their projects.

#### Contribution

I would be willing to help, but I would need some guidance.

**Comment by vietj** [comment]
you should open this in the mutiny vertx generator, now generation happens in each RX / Mutiny project.
