### ISSUE TITLE
add MAX_CLIENT_ID_LENGTH in MqttServerOptions

### ISSUE THREAD

**Issue by dfjb001** [vert-x3/vertx-mqtt#230]
### Questions
 the  length of clientId can not bigger than 23 in the default MqttServer
### Version

4.3.5

### Context

when I use MqttServer, the  length of clientId can not bigger than 23

### Do you have a reproducer?

 I hope you can add the config of  MAX_CLIENT_ID_LENGTH  or expose the getMethod of  NetServer instance

**Comment by mattisonchao** [comment]
@vietj  I can work on it.

**Comment by SivaAkiro** [comment]
is it still open? can i pick it up?
