### ISSUE TITLE
The result of `io.vertx.mqtt.messages.MqttSubscribeMessage.properties()` always be empty

### ISSUE THREAD

**Issue by jpforevers** [vert-x3/vertx-mqtt#249]
### Questions

The result of `io.vertx.mqtt.messages.MqttSubscribeMessage.properties()` always be empty

### Version

4.5.10

### Do you have a reproducer?

Don't need a reproducer. Because the reason for the bug is very obvious, and I have found the cause in the source code.

![image](https://github.com/user-attachments/assets/e4fbac1b-eb2f-40ab-aacd-5c10cfe9f3dc)

As shown in the above figure, in the MqttServerConnection class, the original `io.netty.handler.codec.mqtt.MqttSubscribe` has properties, when converted to io.vertx.mqtt.messages.MqttSubscribe, properties were not included and lost.

Maybe should call another `create` method: `MqttSubscribeMessage create(int messageId, List<io.netty.handler.codec.mqtt.MqttTopicSubscription> topicSubscriptions, MqttProperties properties)` ?

**Comment by jpforevers** [comment]
@vietj @ppatierno Can you help me?

**Comment by vietj** [comment]
sure, we are I think certainly missing a test here in our code at least :-)

**Comment by jpforevers** [comment]
> sure, we are I think certainly missing a test here in our code at least :-)

Thanks and what should we do next? Fix this bug in next version 4.5.11?

**Comment by vietj** [comment]
@jpforevers if you can provide a PR all included that would help us a lot !

**Comment by jpforevers** [comment]
> @jpforevers if you can provide a PR all included that would help us a lot !

Cool. I will try my best.

**Comment by jpforevers** [comment]
@vietj How should I started? I am new to contributing a open source project. 

Is it like this:
1. clone vertx-mqtt to local.
2. create a new branch from master.
3. modify.
4. commit and push.
5. create a PR on Github website.

**Comment by vietj** [comment]
@jpforevers yes thats it make sure you read the guide https://github.com/vert-x3/wiki/wiki/How-to-contribute-to-Vert.x

**Comment by jpforevers** [comment]
@vietj Hello, It seems that I don't have permission to directly create branches in the vertx-mqtt repository, so I use fork to modify and submit PR, is that right way?. This is my PR: #251 , can you have a look.

**Comment by jpforevers** [comment]
@vietj Hello, I have signed ECA. Can you have a look? And what's next now? When I can use this?

Actually, I am implementing an MQTT broker through vertx-mqtt: [VXMQ](https://github.com/jpforevers/vxmq), and need to fix this bug asap so that my MQTT broker can support the MQTT 5 subscription identifier feature. Thanks.

**Comment by jpforevers** [comment]
@vietj Hello？

**Comment by vietj** [comment]
@jpforevers can you provide a PR for the 4.x branch ?

**Comment by jpforevers** [comment]
> @jpforevers can you provide a PR for the 4.x branch ?

@vietj #252

**Comment by vietj** [comment]
@jpforevers thank you for the contribution

**Comment by jpforevers** [comment]
> @jpforevers thank you for the contribution

You're welcome, I'm glad to contribute to the open source project. I want to know, when can I use 4.5.11? 

I like Vert.x and MQTT. Can I have more opportunities to contribute? How to participate?

**Comment by vietj** [comment]
@jpforevers you can come on our discord server and discuss with the community
