### ISSUE TITLE
The question of CONNECT packet check

### ISSUE THREAD

**Issue by ioprotocol** [vert-x3/vertx-mqtt#34]
All handleXXXX methods have do this kind of check except handleConnect method not, because the handleConnect method have a little difference with other handleXXXX methods, Consider this situation: if a client send CONNECT packet twice within one net connection, of course this is not permitted by mqtt 3.1.1 specification for client, but the handleConnect method in MqttConnection class will create another new MqttEndpointImpl Object, which is not conform to specification, While in top level when write a mqtt broker, there will be no method to do this kind of check

**Comment by ppatierno** [comment]
It should be fixed by 322f9e3b756b28d2335ceff053898ef1dbcce56b
