### ISSUE TITLE
Rename client unsubscribeCompleteHandler to unsubscribeCompletionHandler

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-mqtt#45]
usually we use the terminology _completionHandler_ , e.g `MessageConsumer#completionHandler`

**Comment by ppatierno** [comment]
so it should be the same for `publishCompleteHandler` and `subscribeCompleteHandler`. I'm going to do that.

**Comment by ppatierno** [comment]
@vietj I did this for the client with this commit 905ef337601641ea0c4e43de880a074c9daac6de.
There is something similar with the server, should I change it as well ? It will be a breaking change in this case.

**Comment by vietj** [comment]
@ppatierno yes but we are in tech preview, so it is ok-ish, we just need to record it in the wiki page that records the breaking changes for 3.5 : https://github.com/vert-x3/wiki/wiki/3.5.0-Breaking-Changes

**Comment by ppatierno** [comment]
Committed latest changes 5a7372f7517ba74b2fe209a6ced2722e4b650f4c and updated the braking changes page.
