### ISSUE TITLE
Changing client connect API

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-mqtt#48]
We should change the way used today about specifying server host and port to connect (and with latest changes even the SNI server name as well).
They should be just parameters of connect method overloads and should not live inside the MqttClientOptions.
My idea is to remove them from such options that should have only MQTT strictly related options.
Wdyt @vietj @Sammers21?

**Comment by vietj** [comment]
In HttpClient/NetClient we do have default host and port because the same client can reused to connect.

MQTTClient on the contrary does not have notion of _connection_. Perhaps it should ?

**Comment by ppatierno** [comment]
What do you mean with "the same client can reused to connect" ? Where are these default host and port ? Can you elaborate a little bit more ?

**Comment by Sammers21** [comment]
@ppatierno, I think that the idea makes sense.

**Comment by vietj** [comment]
@ppatierno with `NetClient` you typically do

```
NetClient client = vertx.createNetClient();
client.connect(netSocket -> {
  // Obtained a NetSocket, the client has no state
});
```

**Comment by ppatierno** [comment]
@vietj got it ... I think that with a `NetClient` it makes more sense because you write raw bytes on the TCP connection so you work with a `NetSocket`. With the MQTT client you work with higher level API for publishing data, for subscribing to topic, etc ... I think that the current way is more usable.

**Comment by ppatierno** [comment]
I'm going to close with #49
