### ISSUE TITLE
When will this feature be realeased？

### ISSUE THREAD

**Issue by Andy320** [vert-x3/vertx-mqtt#50]
I find it has been now in tech preview for a long time. Thanks.

**Comment by Sammers21** [comment]
@Andy320, what do you mean by "this feature"?

**Comment by Andy320** [comment]
@Sammers21 Sorry for my late response. I mean "vertx-mqtt" is in tech preview period, I am looking forward to it being released.

**Comment by Sammers21** [comment]
@Andy320, I think that @ppatierno or @vietj have some consideration about it. 

But, anyway, it is available in maven central, so you can try to use it and leave your feedback.

**Comment by vietj** [comment]
@Andy320 I think that the mqtt server code is now mature but the mqtt client code will be under tech preview for at least one release

**Comment by Andy320** [comment]
ok. Thanks a lot.
