### ISSUE TITLE
Username/Password Authentification [Question]

### ISSUE THREAD

**Issue by AGutan** [vert-x3/vertx-mqtt#51]
Simple question. 

A bit confused :) 
For what purpose does the client provide the username and password? 
Does the client sign up at first login? 
Who provides the username and password? 
Or should I randomly generate 2 strings as the username and password for each client?

**Comment by ppatierno** [comment]
It's a question related to MQTT protocol and not specific for this project.
Username/Password provides a way for authentication with MQTT protocol and how it works depends on the broker implementation. A broker could have an ACL where clients are allowed to send/receive to/from some topic only after authentication with different rights. 
If your question is related to the client, what you have to put as username/password depends on the broker you are connecting.
If your question is related to the server component then what doing with received username/password is up to you.
