### ISSUE TITLE
MqttAuth and MqttWill as DataObject

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-mqtt#60]
is there a reason these classes couldn't be data object ?

they just contain data and don't have specific behavior.

**Comment by ppatierno** [comment]
no reasons :-) I guess a lack of knowledge on my side when I started to use Vert.x with this project. I'm working on changing them.

**Comment by ppatierno** [comment]
@vietj Starting with `MqttAuth` I get this error on building : 

SEVERE: io.vertx.codegen.CodeGenProcessor - Could not generate model for io.vertx.mqtt.MqttEndpoint#auth(): type io.vertx.mqtt.MqttAuth is not legal for use for a return type in code generation 
io.vertx.codegen.GenException: type io.vertx.mqtt.MqttAuth is not legal for use for a return type in code generation

Isn't it possible to use a @DataObject as a return type of a method ?

**Comment by vietj** [comment]
the data object needs to have a `public JsonObject toJson() { ... }` method

**Comment by ppatierno** [comment]
Fixed with https://github.com/vert-x3/vertx-mqtt/pull/61
