### ISSUE TITLE
Building PR branches

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt#64]
I think that it is a very cool when you can see that all works(or not) directly on a PR page. So having something like that:
![image](https://user-images.githubusercontent.com/16746106/31688593-7c1d23ca-b395-11e7-90b8-e5386fe64e5e.png)

Is it possible to configure building of each PR and attaching of the build results?

Related discussion in Google Groups: https://groups.google.com/forum/#!topic/vertx-dev/e0Q11J6TSM4

**Comment by vietj** [comment]
as said in the google groups, @tsegismont will investigate it on the current Jenkins CI.
