### ISSUE TITLE
Typo in the java docs: 'publishRelease' is used in place of 'publishReceived'

### ISSUE THREAD

**Issue by abasher** [vert-x3/vertx-mqtt#73]
In java doc ([index.adoc](https://github.com/vert-x3/vertx-mqtt/blob/master/src/main/asciidoc/java/index.adoc#handling-client-published-message)) in **Handling client published message** paragraph it is mentioned that *`publishReceived`* needs to be used for Qos of `EXACTLY_ONCE` but in the code block *`publishRelease`* is used instead.

**Comment by Sammers21** [comment]
@abasher, It seems that you are right. Would you mind to fix it?

**Comment by abasher** [comment]
sure, just submitted a pull request

**Comment by ppatierno** [comment]
@abasher thanks ! I have just reviewed it, please take a look ;)

**Comment by abasher** [comment]
Ah, didn't notice docs are auto generated :). Submitted a new pull request.

**Comment by ppatierno** [comment]
Just merged ! Thanks !
