### ISSUE TITLE
checking for memory leak when connect fails

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-mqtt#76]
Hi, 

According to [this issue](https://github.com/vert-x3/vertx-redis-client/issues/97), i have decided to check is there any memory leak in cases when an attempt at establishing a connection is getting failed. 

Here is a reproducer:
```java
       Vertx vertx = Vertx.vertx();
        CountDownLatch countDownLatch = new CountDownLatch(64);
        for (int j = 0; j < 64; j++) {
            new Thread(() -> {
                MqttClient client = MqttClient.create(vertx);
                CyclicBarrier cyclicBarrier = new CyclicBarrier(2);
                for (int i = 0; i < 10000; i++) {
                    client.connect(1883, "localhost", s -> {
                        try {
                            cyclicBarrier.await();
                        } catch (InterruptedException | BrokenBarrierException e) {
                            e.printStackTrace();
                        }
                    });
                    try {
                        cyclicBarrier.await();
                    } catch (InterruptedException | BrokenBarrierException e) {
                        e.printStackTrace();
                    }
                    cyclicBarrier.reset();
                }
                countDownLatch.countDown();
            }).start();
        }
        countDownLatch.await();
        vertx.close();
```

While running this code I was tracking a heap size. Here is how it was changing during the reproducer execution:

![image](https://user-images.githubusercontent.com/16746106/34418567-dfcf217c-ec0f-11e7-83ce-2e951b887d37.png)

So, taking into account the screenshot I would say that there are no memory leaks.

* java version
```java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

* vertx-mqtt version: build based on https://github.com/vert-x3/vertx-mqtt/commit/e616d14b87310cd581c011148e3d45b69b49f7bf

**Comment by Sammers21** [comment]
cc @vietj , @ppatierno

**Comment by Sammers21** [comment]
@vietj, is the reproducer is correct?

**Comment by vietj** [comment]
thanks for the investigation, I will close this issue. The vertx redis client has quite a peculiar behavior with the underlying NetClient implementation.
