### ISSUE TITLE
Client Interoperability between Paho and Vertx: Multi level topics

### ISSUE THREAD

**Issue by Mahaswami** [vert-x3/vertx-mqtt#77]
Great to see MQTT additions to Vertx, Thank you.

We seem to have a issue with client side interoperability. For the server we do use https://github.com/GruppoFilippetti/vertx-mqtt-broker (latest)

* Paho Java client version 1.2.0
* Vertx Java client version 3.5.0

### Multi level topic subscription with # wildcard (Example xxx/report/new/#)

Note: Message sent to xxx/report/new/123

1. Paho to Paho Subscription: works
1. Vertx to Vertx MQTT Client Subscription: works
1. Paho Sent Message is Received by Vertx client subscribing it: works
1. Vertx client sent message receiving by Paho Client: *DOESN'T WORK*

Just to add, in the case where there is a issue single level topic messages sent to wildcard still works.

Any idea what could be leading to this case? Thanks.

**Comment by vietj** [comment]
can you provide a reproducer @Mahaswami for what you are observing ?

**Comment by Mahaswami** [comment]
@vietj  Thank you for looking into this.  Here are the specific test files. I did not include the MQTT Broker which just needs to be running in OOTB configuration and the host names need to be modified in the Maven projects.

[vertx_mqtt_test.zip](https://github.com/vert-x3/vertx-mqtt/files/1610914/vertx_mqtt_test.zip)
[paho_test.zip](https://github.com/vert-x3/vertx-mqtt/files/1610915/paho_test.zip)

**Comment by vietj** [comment]
can you rather provide it as a simple github project that anyone can run to reproduce ?

**Comment by Mahaswami** [comment]
@vietj Sorry I have put the above in github as below and each contains a Readme.txt. BTW, it is pretty much stripped down code. Nothing else really in it.

https://github.com/Mahaswami/paho_mqtt_client_demo
https://github.com/Mahaswami/vertx_mqtt_client_demo

To reproduce the behaviour I mentioned here is what is needed:

1. Run Paho client demo standalone. You should see a message sent by self coming back to the client. **This demonstrates paho to paho working multi level wildcard subscription**
1. Run Vertx client demo standalone. You should see a message sent by self coming back to the client. **This demonstrates vertx to vertx working multi level wild card subscription**
1. Run vertx client demo first and let it keep running. Then run paho client demo. You should see vertx client demo receiving messages sent from paho client demo. **This demonstrates paho -> vertx  working multi level wild card subscription**
1. Run Paho client demo and keep it running. Then run vertx client demo. You WON'T BE SEEING message sent by Vertx received by Paho. **This demonstrates vertx -> paho  NOT WORKING for multi level wild card subscription**

**Comment by Mahaswami** [comment]
@vietj please let me know if something I had missed out in making this easy to reproduce. Thank you for taking the time to look into this.

**Comment by Sammers21** [comment]
@Mahaswami, I tried to simplify your example... so without auth in paho example and unused code. 

Here is what I just created: https://github.com/Sammers21/vertx_paho_mqtt_demo.

And what I observed... it just works fine:
![image](https://user-images.githubusercontent.com/16746106/34668450-8a5bcee4-f47e-11e7-9b33-e27f1559ba85.png)

Can you take a look at my reproducer and make a respond - it is correct reproducer?

**Comment by vietj** [comment]
this issue seems to have been opended in other places and it does not seem to be a real issue - I'm closing it
