### ISSUE TITLE
 Cannot connect to Vertx MQTT Server #1 

### ISSUE THREAD

**Issue by cleberlira** [vert-x3/vertx-mqtt#80]
Hi,

i can not to connect to vertx mqqt server. See message:

java.lang.NoSuchMethodError: io.vertx.core.net.NetClient.connect(ILjava/lang/String;Ljava/lang/String;Lio/vertx/core/Handler;)Lio/vertx/core/net/NetClient;
[INFO] at io.vertx.mqtt.impl.MqttClientImpl.connect(MqttClientImpl.java:136)
[INFO] at io.vertx.book.message.HelloConsumerMicroserviceMqtt.start(HelloConsumerMicroserviceMqtt.java:34)
[INFO] at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
[INFO] at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
[INFO] at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324)
[INFO] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[INFO] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
[INFO] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
[INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[INFO] at java.lang.Thread.run(Thread.java:748)
[INFO] jan 24, 2018 5:35:29 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer

**Comment by vietj** [comment]
make sure you are using the same version of vertx-core and vertx-mqtt
