### ISSUE TITLE
Unsubscribe not working when there is more than 1 client

### ISSUE THREAD

**Issue by kirillkh** [vert-x3/vertx-mqtt#83]
I have two MqttClient's working at the same time (each one in its own verticle). I do the following:
1. subscribe to topic X in client A
2. unsubscribe from topic X in client A
3. subscribe to topic X in client B

The result is that both client A and B now receive all the messages to topic X. I verified in WireShark that only one copy of the packets actually come in from the broker.

**Comment by ppatierno** [comment]
If you are saying that only one packet comes from the broker it's really strange that both clients gets the message. Can you provide the code for reproduce this issue easily (maybe a GutHub repo ?).
Thanks.

**Comment by kirillkh** [comment]
I don't have sample code, the project is closed source.

**Comment by Sammers21** [comment]
@kirillkh, we are not asking for a project source code. We are asking for a code which can be used for reproducing the error.

**Comment by kirillkh** [comment]
All the same, I don't have sample code to reproduce it.

**Comment by kirillkh** [comment]
I'd like to add that both clients are connected to the same server, but they use different client ids.

**Comment by ppatierno** [comment]
Even if your code is closed source it should be simple for you to write a simple application to reproduce the problem.

**Comment by kirillkh** [comment]
Thank you for suggestion! I explained exactly what I did, so anyone should be able to reproduce it. Doesn't vertx-mqtt have test infrastructure to enable writing such test cases easily?

**Comment by kirillkh** [comment]
Can't someone knowledgeable in vertx-mqtt test infrastructure do it?

**Comment by kirillkh** [comment]
I don't really understand why you decided that handling this bug is my responsibility. I found it and described the steps to reproduce, but how does that automatically make me responsible for a writing test case?

**Comment by ppatierno** [comment]
@kirillkh I'm not deciding that, I'm just asking if it's possible getting an example from you. I can do that (when possible) and then come up with (maybe?) something working and then the problem should be compare my code with yours with wasting of time. It seems to me that you don't get how open source works; if you want the "potential" bug fixed right now you could investigate and provide a PR for that otherwise you can wait for us fixing it.

**Comment by kirillkh** [comment]
@ppatierno I do understand how open source works. If reproducing it were easy, I'd do it right now. But from my perspective reproducing it is quite a lot of code: you need to set up the broker, two subscribers and then a publisher as well. I assume that vertx-mqtt has test infrastructure that enables writing such tests easily. Hence it would be better if one of the project developers did it.

**Comment by ppatierno** [comment]
We'll do that. Wait for us please.

**Comment by kirillkh** [comment]
Look, I might be able to do it if you point me to a test case that already implements subscriber+broker+publisher and needs little modification to implement two subscribers.

**Comment by ppatierno** [comment]
@kirillkh I have added a test for this scenario and it passes without any problems. It's the new `unsubscribedNoMessageReceived` method under `MqttClientSubscribeTest` class.
Two clients connects to the Eclipse public MQTT broker (based on Mosquitto) and subscribe to a topic then the first client unsubscribe. Finally, a publisher publishes a message but just only the second client (still subscribed) gets the message.

**Comment by ppatierno** [comment]
@kirillkh any news on that before I close this "issue" ?

**Comment by kirillkh** [comment]
I don't like your tone, but I'm working on it.

**Comment by ppatierno** [comment]
@kirillkh what do you mean ? I was just asking because you pushed on this issue without giving any example for reproducing it (which is something that all developers interested in the project do and they are really helpful for us). I wrote a test and it's working so there is no issue for me (but I could be wrong). This was my concern : it's always better to provide a reproducer code in order to be sure that the issue is really there. I think you should think about your approach in the community.

**Comment by kirillkh** [comment]
I realize that you feel your time has been wasted, but I had my own reasoning for not readily providing reproducible test case, I explained it, and you seemed to agree. If you hadn't did it, I would've done it myself. Anyway, please be patient while I'm trying to reproduce the issue and figure out where it's failing.

**Comment by ppatierno** [comment]
@kirillkh my time isn't wasted absolutely. As maintainer of this project I want to fix all the issues that users report to me but sometime happens that the bug depends on the environment where users are using the library. For this reason a developer should isolate the problem providing a reproducible and simple code. This is the case : my test is working so from my point of view there is no bug but you know better then me the environment where you are using the library and can provide an example for that. Just this.

**Comment by kirillkh** [comment]
The problem was in our code. Thank you for helping with the test case.

**Comment by ppatierno** [comment]
Happy to help ;)

**Comment by sophokles73** [comment]
@ppatierno I wish I had your nerves ;-)

**Comment by ppatierno** [comment]
@sophokles73 they have been severely tested ;-)
