### ISSUE TITLE
Vertx mqtt server not work with MqttCalback

### ISSUE THREAD

**Issue by cleberlira** [vert-x3/vertx-mqtt#88]
Hi,

I am trying to access the Vert.x mqtt server from client paho but method callback not work.  I need help for to solution.  Folowing the implementation of Vert.x Mqtt Server and client paho.

i have implementation of according with: https://vertx.io/docs/vertx-mqtt-server/java/.  

@Component(immediate = true)
@Instantiate
public class VertxMqtt extends AbstractVerticle{

    public static final String MQTT_SERVER_HOST = "localhost";
    public static final int MQTT_SERVER_PORT = 1883;

   

    private static final Logger LOG = LoggerFactory.getLogger(VertxMqtt.class);

    public void init() {
        System.out.println("Inicializando Vertx");
    }

    private static void handleSubscription(MqttEndpoint endpoint) {
        endpoint.subscribeHandler(subscribe -> {

            List grantedQosLevels = new ArrayList<>();
            for (MqttTopicSubscription s : subscribe.topicSubscriptions()) {

                LOG.info("Subscription for " + s.topicName() + " with QoS " + s.qualityOfService());
                System.out.println("Subscription for " + s.topicName() + " with QoS " + s.qualityOfService());

                grantedQosLevels.add(s.qualityOfService());
            }

            endpoint.subscribeAcknowledge(subscribe.messageId(), grantedQosLevels);

        });
    }

    private static void handleUnsubscription(MqttEndpoint endpoint) {
        endpoint.unsubscribeHandler(unsubscribe -> {

            for (String t : unsubscribe.topics()) {
                LOG.info("Unsubscription for " + t);
            }

            endpoint.unsubscribeAcknowledge(unsubscribe.messageId());
        });
    }

    
    private static void publishHandler(MqttEndpoint endpoint) {

        System.out.println("MQTT client [{}] connected" + endpoint.clientIdentifier());

        LOG.info("MQTT client [{}] connected", endpoint.clientIdentifier());

        endpoint.publishHandler(message -> {

            LOG.info("Just received message [" + message.payload().toString(Charset.defaultCharset()) + "] with QoS [" + message.qosLevel() + "]");
            System.out.println("Just received message [" + message.payload().toString(Charset.defaultCharset()) + "] with QoS [" + message.qosLevel() + "]");

            if (message.qosLevel() == MqttQoS.AT_LEAST_ONCE) {
               
              endpoint.publishAcknowledge(message.messageId());
            } else if (message.qosLevel() == MqttQoS.EXACTLY_ONCE) {
                endpoint.publishRelease(message.messageId());
            }

        }).publishReleaseHandler(messageId -> {
            
            System.out.println("vertx " + "publishComplete"  );
               
            endpoint.publishComplete(messageId);
        });

    }

    private static void handleClientDisconnect(MqttEndpoint endpoint) {
        endpoint.disconnectHandler(h -> {
            System.out.println("The remote client has closed the connection.");
            LOG.info("The remote client has closed the connection.");
        });
    }

    @Validate
    public void test() throws Exception {

        MqttServerOptions opts = new MqttServerOptions();
        opts.setHost(MQTT_SERVER_HOST);
        opts.setPort(MQTT_SERVER_PORT);

        Vertx vertx = executeWithTCCLSwitch(() -> Vertx.vertx());
        
        System.out.println("MqttServer" + vertx);

        MqttServer mqttServer = executeWithTCCLSwitch(() -> MqttServer.create(vertx, opts));

        System.out.println("star conectadno");
        mqttServer.endpointHandler(endpoint -> {

            System.out.println("star conectadno 2");
            // accept connection from the remote client
            endpoint.accept(false);

            handleSubscription(endpoint);

            System.out.println("star conectadno 3");
            handleUnsubscription(endpoint);
            publishHandler(endpoint);
            handleClientDisconnect(endpoint);
            // shows main connect info
            LOG.info("MQTT client [" + endpoint.clientIdentifier() + "] request to connect, clean session = " + endpoint.isCleanSession());

            if (endpoint.auth() != null) {
                System.out.println("[username = " + endpoint.auth().userName() + ", password = " + endpoint.auth().password() + "]");
            }
           
          
            if (endpoint.will() != null) {
                System.out.println("[will topic = " + endpoint.will().willTopic() + " msg = " + endpoint.will().willMessage()
                        + " QoS = " + endpoint.will().willQos() + " isRetain = " + endpoint.will().isWillRetain() + "]");
            }

            
            LOG.info("[keep alive timeout = " + endpoint.keepAliveTimeSeconds() + "]");

        })
                .listen(ar -> {

                    if (ar.succeeded()) {

                        LOG.info("MQTT server is listening on port " + ar.result().actualPort());
                        System.out.println("MQTT server is listening on port " + ar.result().actualPort());

                    } else {

                        LOG.error("Error on starting the server");
                        ar.cause().printStackTrace();
                    }
                });

        //vertx.close();
       
       
       // Sharing mqtt server
       // DeploymentOptions options = new DeploymentOptions().setInstances(2);
       // vertx.deployVerticle("br.ufba.dcc.wiser.VertxMqtt", options);
    }

}

**# Implementation of client paho for access Vert.x MqttServer:**

public class PublisherPaho implements MqttCallback {

    private static int counter = 0;

    public PublisherPaho() {

        Vertx vertx = Vertx.vertx();

        try {

            MemoryPersistence persistence = new MemoryPersistence();
            MqttClient client = new MqttClient(String.format("tcp://%s:%d", "localhost", 1883), "pub-0", persistence);

            MqttConnectOptions opt = new MqttConnectOptions();

            opt.setCleanSession(false);
            
            opt.setKeepAliveInterval(30);
	    opt.setAutomaticReconnect(true);
        
            client.setCallback(this);

            client.connect(opt);
            
            client.subscribe("reactivetentando", 1);
		     
            
                    client.publish("reactivetentando",
                          ("reactive microservices client paho " + counter++).getBytes(),
                           1,
                            false);
            
            System.out.println("Connected to the broker.. ");
            

            System.in.read();
        //    client.disconnect();

            vertx.close();

        } catch (IOException | MqttException e) {
            e.printStackTrace();
        }

    }

    public static void main(String[] args) throws MqttException {

        PublisherPaho p = new PublisherPaho();

    }

    @Override
    public void connectionLost(Throwable thrwbl) {
        Vertx vertx = Vertx.vertx();

        try {

            MemoryPersistence persistence = new MemoryPersistence();
            MqttClient client = new MqttClient(String.format("tcp://%s:%d", "localhost", 1883), "pub-0", persistence);

            MqttConnectOptions opt = new MqttConnectOptions();

            opt.setUserName("karaf");
            opt.setPassword("karaf".toCharArray());

            client.setCallback(this);
            client.connect(opt);
//            vertx.setPeriodic(1000, time -> {

                try {

                    client.subscribe("REACTIVE");

                    client.publish("REACTIVE",
                            ("reactive microservices client paho " + counter++).getBytes(),
                            1,
                            false);

                } catch (MqttException ex) {
                    System.out.println("erro 2" + ex.getMessage());
                    ex.printStackTrace();
                }

  //          });

            System.in.read();
            //client.disconnect();

            vertx.close();

        } catch (IOException | MqttException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void messageArrived(String string, MqttMessage mm) throws Exception {
       System.out.println("-------------------------------------------------");
		System.out.println("| Topic:" + string);
		System.out.println("| Message: " + new String(mm.getPayload()));
		System.out.println("-------------------------------------------------");
    }

    @Override
    public void deliveryComplete(IMqttDeliveryToken imdt) {
        try {
            String message = new String(imdt.getMessage().getPayload());
            System.out.println("deliveryComplet " + message);
        } catch (MqttException e) {
            System.out.println(e.getMessage());
        }
    }
}

**Comment by cleberlira** [comment]
@*Sammers21* , can you please to access at:
https://github.com/WiserUFBA/vertx-mqttt-client

Open the file Instructions.

Thanks


2018-04-12 18:23 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by Sammers21** [comment]
Hi @cleberlira, I will take a look at it on the next week. Please keep tuned.

**Comment by Sammers21** [comment]
Hi  @cleberlira, I have a look at your project. If you wonder why `PublisherPaho#messageArrived` is not called, the reason is that you are not sending it on the server side.

Vert.x MQTT server is designed in a way, to handle subscription by hands, not automatically. So basically, the client will receive a message if you would call `MqttEndpoint#publish`.

**Comment by Sammers21** [comment]
@cleberlira , you should also pay attention to the line: https://github.com/WiserUFBA/vertx-mqttt-client/blob/master/src/main/java/br/ufba/dcc/wiser/PublisherPaho.java#L128, I figured out that you are getting `java.lang.NullPointerException` here

**Comment by cleberlira** [comment]
Ok. I understand but in my project original i need to publish message when
happen subscriptions.  I dont know to handle message this moment.  How do I
get access to payload?


             endpoint.subscribeAcknowledge(subscribe.messageId(),
grantedQosLevels);

                        System.out.println("endpointcantes " +
endpoint.clientIdentifier());

                       for (MqttTopicSubscription s :
subscribe.topicSubscriptions()) {
                            endpoint.publish(s.topicName(),
                          *  Buffer.buffer("teste"),*
                                  s.qualityOfService(),
                                  false,
                                  false);

                        }

2018-04-24 10:21 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by cleberlira** [comment]
Hi @Pavel Drankov,

i too tested mqtt client of according with o link (
https://vertx.io/blog/introducing-vert-x-mqtt-client/) and not working.

i too tested mqtt client of according with o link (
https://vertx.io/blog/introducing-vert-x-mqtt-client/) and not working.
i cant get message from the topics i am subscribing for.




2018-04-26 15:02 GMT-03:00 Cleber Lira <cleberlira@gmail.com>:

**Comment by cleberlira** [comment]
The vertx is only listening to messages from it.

2018-04-12 18:23 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by cleberlira** [comment]
@*Sammers21* ,

can you please to access at:
https://github.com/cleberlira/iotvirtualdevice/blob/master/instructions
I can not consume the messages for the topics that the client is subscribed
to. I tested using Mqtt Client and the paho client but it does not work.

It only works when I do a publish of the subscribed topic in the Client
itself


Thanks


2018-04-27 13:58 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by Sammers21** [comment]
>can you please to access at:
>https://github.com/cleberlira/iotvirtualdevice/blob/master/instructions

I will look at it. But before, can you access mqtt-examples(https://github.com/vert-x3/vertx-examples/tree/master/mqtt-examples) and try one of them? Maybe you will be able to figure out what is wrong by looking at the examples?

**Comment by cleberlira** [comment]
Hi,

I've done this...

2018-04-28 7:25 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by Sammers21** [comment]
@cleberlira , have you solved the problem?

**Comment by cleberlira** [comment]
@*Sammers21* , I understand that Vertx MQTT not a MQTT broker.

Is there prevision to support featured broker?


Thanks

Cleber Lira


2018-05-09 14:21 GMT-03:00 Pavel Drankov <notifications@github.com>:

**Comment by Sammers21** [comment]
@cleberlira, Vert.x MQTT provides a set of tools for building an MQTT broker, it also has a full-featured MQTT client.

Nope, we are not planning to create a featured broker on it. Instead, we are giving you convenient tools for building one.

**Comment by sandipsahoo2k2** [comment]
I am using vertx mqtt server for my www.feettrack.com server and all is well .. Note its not a full fledge MQTT Broker so dont  misunderstand with a complete MQTT server.. You need to had write a lot of publsih and suscribe and manage cache of client connection etc to be able to use it as per your need.
