### ISSUE TITLE
https://vertx.io/docs/vertx-mqtt/kotlin/ can not show the code in : Handling client connection/disconnection

### ISSUE THREAD

**Issue by dushibaiyu** [vert-x3/vertx-mqtt#98]
it show : Code not translatable

in opera 53.0
win10

**Comment by ppatierno** [comment]
@vietj any idea about that?

**Comment by vietj** [comment]
it's because the example cannot be translated from java to Kotlin by the code translator

**Comment by vietj** [comment]
which example is it in our codebase ? can you point it out ?
